name: ilpselect
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.4
  - pip=24.3.1
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.3.0
  - skmatter=0.2.0
  - plotly=5.24.1
  - blas=1.1=openblas
  - lapack=3.9.0=netlib
  - pip:
      - qmllib==1.1.5
      - kaleido==0.2.1
      - gurobipy==10.0.2
